/*
 * system.h
 *
 *  Created on: 26.11.2020
 *      Author: Autogenerated
 */
#ifndef __SYSTEM_H
#define __SYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32l4xx_hal.h"

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void);

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void);


#ifdef __cplusplus
}
#endif

#endif
